### ISSUE TITLE
学长你好我最近在做这个死锁解除的课设

### ISSUE THREAD

**Issue by SoYoungHa** [DolorHunter/OS_PR-DR#1]
正好在github上看到了学长你您的代码，不知道学长有没有更加详细的注解

**Comment by DolorHunter** [comment]
```c
typedef struct ResourceAllocation{
    int proNum;                                  // 初始进程数
    int process[MAX_PROCESS];                    // 进程表
    int resource[MAX_RESOURCE];                  // 资源表
    int resApply[MAX_PROCESS][MAX_RESOURCE];     // 资源申请表
    int resAllocate[MAX_PROCESS][MAX_RESOURCE];  // 资源分配表
    int relResource[MAX_RESOURCE];               // 可释放资源表
    int relProcess[MAX_PROCESS];                 // 可释放进程表
    int relProPos;                               // 可释放资源表位置
    int leftProNum;                              // 剩余进程数
    int resProcess[MAX_PROCESS];                 // 释放进程表
    int searchProcess[INF][4];                   // 记录搜索历史
    int seaProPos;                               // 记录搜索位置
}ResourceAllocation;
```

- void initDeadlockRecovery(ResourceAllocation *rA); 初始化死锁恢复
- void initRelProcess(ResourceAllocation *rA); 初始化释放进程
- void genRelProcess(ResourceAllocation *rA); 生成释放进程表
- int isReleasable(ResourceAllocation *rA, int pro); 进程是否可释放
- void saveSearchProcess(ResourceAllocation *rA, int i, int applyRes, int relRes, int bestProcess); 保存查找过程
- int bestRes2Release(ResourceAllocation *rA); 查找最佳释放进程
- void addResProcess(ResourceAllocation *rA, int pro); 加入剩余进程
- void relProcess(ResourceAllocation *rA, int pro); 释放进程
- void deadlockRecovery(ResourceAllocation *rA); 死锁恢复
- void prtSearchProcess(ResourceAllocation *rA); 打印查找过程
- void prtResourceAllocation(ResourceAllocation *rA); 打印资源分配

https://github.com/DolorHunter/OS_PR-DR/blob/2d7177d926e6d87e4ae3c5e59339b7933bd5021b/DeadlockRecovery/src/deadlockRecovery.h#L27

---

#### void genRelProcess(ResourceAllocation *rA) 生成可释放进程表

遍历资源表, 如果当前资源>所有进程申请此资源, 即认为资源可释放. 遍历进程, 统计 count, 如果当前进程拥有最大资源, 更新可释放资源表的值, 清空 count, 继续遍历下一个资源.

https://github.com/DolorHunter/OS_PR-DR/blob/2d7177d926e6d87e4ae3c5e59339b7933bd5021b/DeadlockRecovery/src/deadlockRecovery.c#L41

#### int isReleasable(ResourceAllocation *rA, int pro) 判断是否可释放

https://github.com/DolorHunter/OS_PR-DR/blob/2d7177d926e6d87e4ae3c5e59339b7933bd5021b/DeadlockRecovery/src/deadlockRecovery.c#L76

#### int bestRes2Release(ResourceAllocation *rA) 寻找最佳释放进程

遍历进程, 如果当前进程存在且可释放, 遍历资源计算该进程总的申请资源和释放资源.如果该进程的总申请资源最小且可释放资源最大, 认为进程为最佳释放进程.

https://github.com/DolorHunter/OS_PR-DR/blob/2d7177d926e6d87e4ae3c5e59339b7933bd5021b/DeadlockRecovery/src/deadlockRecovery.c#L94

#### void relProcess(ResourceAllocation *rA, int pro) 释放进程

https://github.com/DolorHunter/OS_PR-DR/blob/2d7177d926e6d87e4ae3c5e59339b7933bd5021b/DeadlockRecovery/src/deadlockRecovery.c#L133

其他函数比较简单, 当时文档就只写了这几个func.

**Comment by SoYoungHa** [comment]
谢谢学长啦😀
