### ISSUE TITLE
页面置换中的so不能使用是怎么回事呢？

### ISSUE THREAD

**Issue by 10422ytl** [DolorHunter/OS_PR-DR#2]
你好，请问一下so文件在python下不能使用是什么情况？并且我查看了下你的cmakelist中发现多了timer2的c文件，但是在src下并没有，所以想问问是怎么回事，感谢！

**Comment by DolorHunter** [comment]
timer2 的展示用C实现有逻辑冲突，用 C 实现必须把GUI演示的逻辑写在功能内，但是是用 Python 做的 GUI。如果要这么做的话就得 Python (GUI) 调用 C (线程计时)调用Python (GUI添加数据)，有点麻烦而且奇怪。所以就直接在 Python 里面用线程库写了一个 timer2，实际上用的也是这个做 timer2。timer2.c  一开始有写，但是并没有用处就删掉了。
https://github.com/DolorHunter/OS_PR-DR/blob/2d7177d926e6d87e4ae3c5e59339b7933bd5021b/PagesReplacement/gui.py#L297
